version: '3.3'

services:
    postgres:
        image: postgres
        environment:
         - POSTGRES_PASSWORD=password
         - POSTGRES_DB=tryton
    
    tryton:
        image: tryton/tryton
        ports:
         - '8000:8000'
        depends_on:
         - postgres
        environment:
         - DB_USER=user
         - DB_PASSWORD=password
         - DB_HOSTNAME=tryton-postgres
         - DB_PORT=5432
