version: "2"
services:
    postgres:
        image: postgres
        container_name: postgres
        environment:
            POSTGRES_USER: "tryton"
            POSTGRES_PASSWORD: "password"
            POSTGRES_DB: "tryton-test"

    tryton:
        image: tryton/tryton
        container_name: tryton
        depends_on:
            - postgres
        environment:
            TRYTOND_DATABASE_URI: postgresql://tryton:password@postgres:5432/
            DB_USER: "tryton"
            DB_PASSWORD: "password"
            DB_HOSTNAME: "postgres"
        ports:
            - "8000:8000"
