version: "2"
services:
    postgres:
        image: postgres
        container_name: postgres
        environment:
            POSTGRES_USER: "triton"
            POSTGRES_PASSWORD: "triton"
            POSTGRES_DB: "tryton-test"

    tryton:
        image: tryton/tryton
        container_name: tryton
        command: trytond-admin -d tryton-test --all -vv
        depends_on:
            - postgres
        environment:
            TRYTOND_DATABASE_URI: postgresql://triton:triton@postgres:5432/
            DB_USER: "triton"
            DB_PASSWORD: "triton"
            DB_HOSTNAME: "postgres"
        ports:
            - "8000:8000"
