version: '3.3'

services:
    tryton:
        image: tryton/tryton
        ports:
         - '8000:8000'
        depends_on:
         - tryton-postgres
        environment:
         - DB_USER=user
         - DB_PASSWORD=password
         - DB_HOSTNAME=postgres
         - DB_PORT=5432
         
    tryton-postgres:
        image: postgres
        environment:
         - POSTGRES_USER=user
         - POSTGRES_PASSWORD=password
         - POSTGRES_DB=tryton
    
