version: '3.3'
services:

    tryton:
        image: tryton/tryton
        ports:
         - '8000:8000'
        link:
         - 'tryton-postgres:postgres'
         environment:
         - DB_PASSWORD=tryton
          
    tryton-postgres:
        image: postgres
        environment:
         - POSTGRES_USER=tryton
         - POSTGRES_PASSWORD=tryton
         - POSTGRES_DB=tryton
